(setq omni-contacts--data
      '(
        ((first-name . "John")
         (last-name . "Shepard")
         (title . "N7 Alliance Marine / Spectre")
         (race . "Human")
         (gender . "Male"))
        ((first-name . "Jane")
         (last-name . "Shepard")
         (title . "N7 Alliance Marine / Spectre")
         (race . "Human")
         (gender . "Female"))
        ((first-name . "Kaidan")
         (last-name . "Alenko")
         (title . "Systems Alliance Sentinel")
         (race . "Human")
         (gender . "Male"))
        ((first-name . "Ashley")
         (last-name . "Williams")
         (title . "System Alliance Soldier")
         (race . "Human")
         (gender . "Female"))
        ((first-name . "Liara")
         (last-name . "T'Soni")
         (title . "Asari Scientist")
         (race . "Asari")
         (gender . "Feminine"))
        ((first-name . "Garrus")
         (last-name . "Vakarian")
         (title . "Turian Agent")
         (race . "Turian")
         (gender . "Male"))
        ((clan-name . "Urdnot")
         (first-name . "Wrex")
         (title . "Krogan Battlemaster")
         (race . "Krogan")
         (gender . "Male"))
        ((first-name . "Tali'Zorah")
         (last-name . "var Normandy")
         (title . "Quarian Machinist")
         (race . "Quarian")
         (gender . "Female"))

        ((first-name . "Miranda")
         (last-name . "Lawson")
         (title . "Cerberus Officer")
         (race . "Human")
         (gender . "Female"))
        ((first-name . "Jacob")
         (last-name . "Taylor")
         (title . "Cerberus Operative")
         (race . "Human")
         (gender . "Male"))
        ((first-name . "Mordin")
         (last-name . "Solus")
         (title . "Salarian Scientist")
         (race . "Salarian")
         (gender . "Male"))
        ((first-name . "Jacqueline")
         (last-name . "Nought")
         (title . "Subject Zero")
         (race . "Human")
         (gender . "Female"))
        ((clan-name . "Urdnot")
         (first-name . "Grunt")
         (title . "Krogan Berserker")
         (race . "Krogan")
         (gender . "Male"))
        ((first-name . "Thane")
         (last-name . "Krios")
         (title . "Drell Assassin")
         (race . "Drell")
         (gender . "Male"))
        ((first-name . "Samara")
         (suffix . "")
         (title . "Asari Justicar")
         (race . "Asari")
         (gender . "Feminine"))
        ((first-name . "Legion")
         (suffix . "")
         (title . "Geth Infiltrator")
         (race . "Geth"))
        ((first-name . "Zaeed")
         (last-name . "Massani")
         (title . "Mercenary Veteran")
         (race . "Human")
         (gender . "Male"))
        ((first-name . "Kasumi")
         (last-name . "Goto")
         (title . "Master Thief")
         (race . "Human")
         (gender . "Female"))

        ((first-name . "James")
         (last-name . "Vega")
         (title . "Arms Master")
         (race . "Human")
         (gender . "Male"))
        ((first-name . "EDI")
         (suffix . "")
         (title . "Cerberus Artificial Intelligence")
         (race . "Artificial Intelligence")
         (gender . "Female"))
        ((first-name . "Javik")
         (suffix . "")
         (title . "Vengeful Ancient")
         (race . "Prothean")
         (gender . "Male"))
        ))
