(setq organic-contacts--data
      '(
        (("John" "Shepard")
         ("me1" "me2" "me3")
         (title . "N7 Alliance Marine / Spectre")
         (race . "Human")
         (gender . "Male"))
        (("Jane" "Shepard")
         ("me1" "me2" "me3")
         (title . "N7 Alliance Marine / Spectre")
         (race . "Human")
         (gender . "Female"))
        (("Kaidan" "Alenko")
         ("me1" "me3")
         (title . "Systems Alliance Sentinel")
         (race . "Human")
         (gender . "Male"))
        (("Ashley" "Williams")
         ("me1" "me3")
         (title . "System Alliance Soldier")
         (race . "Human")
         (gender . "Female"))
        (("Liara" "T'Soni")
         ("me1" "me3")
         (title . "Asari Scientist")
         (race . "Asari")
         (gender . "Feminine"))
        (("Garrus" "Vakarian")
         ("me1" "me2" "me3")
         (title . "Turian Agent")
         (race . "Turian")
         (gender . "Male"))
        (("Urdnot" "Wrex")
         ("me1" "me3")
         (title . "Krogan Battlemaster")
         (race . "Krogan")
         (gender . "Male"))
        (("Tali'Zorah" "vas Normandy")
         ("me1" "me2" "me3")
         (title . "Quarian Machinist")
         (race . "Quarian")
         (gender . "Female"))

        (("Miranda" "Lawson")
         ("me2")
         (title . "Cerberus Officer")
         (race . "Human")
         (gender . "Female"))
        (("Jacob" "Taylor")
         ("me2")
         (title . "Cerberus Operative")
         (race . "Human")
         (gender . "Male"))
        (("Mordin" "Solus")
         ("me2")
         (title . "Salarian Scientist")
         (race . "Salarian")
         (gender . "Male"))
        (("Jacqueline" "Nought")
         ("me2")
         (title . "Subject Zero")
         (race . "Human")
         (gender . "Female"))
        (("Urdnot" "Grunt")
         ("me2")
         (title . "Krogan Berserker")
         (race . "Krogan")
         (gender . "Male"))
        (("Thane" "Krios")
         ("me2")
         (title . "Drell Assassin")
         (race . "Drell")
         (gender . "Male"))
        (("Samara")
         ("me2")
         (title . "Asari Justicar")
         (race . "Asari")
         (gender . "Feminine"))
        (("Legion")
         ("me2")
         (title . "Geth Infiltrator")
         (race . "Geth"))
        (("Zaeed" "Massani")
         ("me2")
         (title . "Mercenary Veteran")
         (race . "Human")
         (gender . "Male"))
        (("Kasumi" "Goto")
         ("me2")
         (title . "Master Thief")
         (race . "Human")
         (gender . "Female"))

        (("James" "Vega")
         ("me3")
         (title . "Arms Master")
         (race . "Human")
         (gender . "Male"))
        (("EDI")
         ("me3")
         (title . "Cerberus Artificial Intelligence")
         (race . "Artificial Intelligence")
         (gender . "Female"))
        (("Javik")
         ("me3")
         (title . "Vengeful Ancient")
         (race . "Prothean")
         (gender . "Male"))
        ))
